// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

package test

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}
func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (m *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(m, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

type TestRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}
func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (m *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(m, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

func (m *TestRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TestReply struct {
	Answer               string   `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestReply) Reset()         { *m = TestReply{} }
func (m *TestReply) String() string { return proto.CompactTextString(m) }
func (*TestReply) ProtoMessage()    {}
func (*TestReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}
func (m *TestReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestReply.Unmarshal(m, b)
}
func (m *TestReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestReply.Marshal(b, m, deterministic)
}
func (m *TestReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestReply.Merge(m, src)
}
func (m *TestReply) XXX_Size() int {
	return xxx_messageInfo_TestReply.Size(m)
}
func (m *TestReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TestReply.DiscardUnknown(m)
}

var xxx_messageInfo_TestReply proto.InternalMessageInfo

func (m *TestReply) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

var E_Publish = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         2360,
	Name:          "natsrpc.publish",
	Tag:           "varint,2360,opt,name=publish",
	Filename:      "test.proto",
}

func init() {
	proto.RegisterType((*Nil)(nil), "natsrpc.Nil")
	proto.RegisterType((*TestRequest)(nil), "natsrpc.TestRequest")
	proto.RegisterType((*TestReply)(nil), "natsrpc.TestReply")
	proto.RegisterExtension(E_Publish)
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x0d, 0xf6, 0x8f, 0x1d, 0x3d, 0x0d, 0x22, 0xa5, 0x07, 0x89, 0x29, 0x42, 0x4f, 0x1b,
	0xda, 0x9e, 0xd4, 0x9b, 0x57, 0xff, 0x41, 0xf4, 0xe4, 0x2d, 0x49, 0xc7, 0x64, 0x61, 0x9b, 0x5d,
	0x77, 0x27, 0x95, 0x7e, 0x0e, 0xbf, 0x8c, 0x47, 0x3f, 0x9a, 0x6c, 0x92, 0x8a, 0x08, 0xbd, 0x2c,
	0x3b, 0x8f, 0xdf, 0xec, 0x7b, 0x6f, 0x01, 0x98, 0x1c, 0x0b, 0x63, 0x35, 0x6b, 0x1c, 0x56, 0x29,
	0x3b, 0x6b, 0xf2, 0x49, 0x58, 0x68, 0x5d, 0x28, 0x8a, 0x1b, 0x39, 0xab, 0xdf, 0xe2, 0x15, 0xb9,
	0xdc, 0x4a, 0xc3, 0xda, 0xb6, 0x68, 0xd4, 0x87, 0xc3, 0x47, 0xa9, 0xa2, 0x0b, 0x38, 0x7e, 0x21,
	0xc7, 0x09, 0xbd, 0xd7, 0xe4, 0x18, 0x11, 0x7a, 0x55, 0xba, 0xa6, 0x71, 0x10, 0x06, 0xb3, 0x51,
	0xd2, 0xdc, 0xa3, 0x29, 0x8c, 0x5a, 0xc4, 0xa8, 0x2d, 0x9e, 0xc1, 0x20, 0xad, 0xdc, 0x07, 0xd9,
	0x0e, 0xe9, 0xa6, 0x05, 0x03, 0x78, 0xe8, 0x99, 0xec, 0x86, 0x2c, 0x2e, 0xa1, 0xef, 0xa7, 0x39,
	0x9e, 0x8a, 0x2e, 0x91, 0xf8, 0xe3, 0x32, 0xc1, 0x7f, 0xaa, 0x51, 0xdb, 0xe8, 0x00, 0xe7, 0xed,
	0xd2, 0x62, 0xcf, 0xd2, 0xc9, 0xaf, 0xea, 0x73, 0xf7, 0xbe, 0x3f, 0x83, 0xe0, 0xfa, 0x0a, 0x86,
	0xa6, 0xce, 0x94, 0x74, 0x25, 0x9e, 0x8b, 0xb6, 0xb2, 0xd8, 0x55, 0x16, 0x0f, 0xc4, 0xa5, 0x5e,
	0x3d, 0x19, 0x96, 0xba, 0x72, 0xe3, 0x2f, 0x0c, 0x83, 0xd9, 0x51, 0xb2, 0xe3, 0x6f, 0x2f, 0x5f,
	0xa7, 0x85, 0xe4, 0xb2, 0xce, 0x44, 0xae, 0xd7, 0xf1, 0x3d, 0xdd, 0xe9, 0x8d, 0x8d, 0x3b, 0x87,
	0xd8, 0x7f, 0xe9, 0x8d, 0x3f, 0xb2, 0x41, 0xf3, 0xdc, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x11,
	0x73, 0xe5, 0x61, 0x66, 0x01, 0x00, 0x00,
}
